using LogicLayer;
using LogicLayerInterfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WPFPresentationLayer
{
    /// <summary>
    /// NAME: Zach Behrensmeyer
    /// DATE: 2/20/2020
    /// CHECKED BY: NA
    /// 
    /// This class controls LogView page
    /// 
    /// </summary>
    public partial class LogView : Page
    {

        private ILogManager _logManager; 

        /// <summary>
        /// NAME: Zach Behrensmeyer
        /// DATE: 2/20/2020
        /// CHECKED BY: 
        /// 
        /// This is a constructor for the LogView Page
        /// 
        /// </summary>
        /// <remarks>
        /// UPDATED BY: NA
        /// UPDATED NA
        /// CHANGE: NA
        /// 
        /// </remarks>
        /// </summary>
        public LogView()
        {
            _logManager = new LogManager();
            InitializeComponent();
        }

        /// CREATOR: Zach Behrensmeyer
        /// CREATED: 02/15/2020
        /// APPROVER: Steven Cardona
        /// 
        /// Method that generates the columns for the log list.
        /// </summary>
        /// <remarks>
        /// UPDATER: N/A
        /// UPDATED: N/A
        /// UPDATE: N/A        
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgLogList_AutoGeneratedColumns_1(object sender, EventArgs e)
        {
            dgLogList.Columns.RemoveAt(6);
            dgLogList.Columns.RemoveAt(4);
            dgLogList.Columns.RemoveAt(2);
            dgLogList.Columns.RemoveAt(0);
            dgLogList.Columns[0].Header = "Log Date";
            dgLogList.Columns[1].Header = "Log Level";
            dgLogList.Columns[2].Header = "Log Message";

            foreach (var column in this.dgLogList.Columns)
            {
                column.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            }
        }


        /// <summary>
        /// CREATOR: Zach Behrensmeyer
        /// CREATED: 02/15/2020
        /// APPROVER: Steven Cardona
        /// 
        /// When dgLogList is loaded. Adds items into dgLogList.
        /// </summary>
        /// <remarks>
        /// UPDATED BY: N/A
        /// UPDATED: N/A
        /// UPDATE: N/A
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgLogList_Loaded(object sender, RoutedEventArgs e)
        {
            dgLogList.ItemsSource = _logManager.RetrieveLoginandOutLogs();
        }
    }
}
