using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using LogicLayer;
using LogicLayerInterfaces;
using DataTransferObjects;

namespace WPFPresentationLayer.AdoptionPages
{
    /// <summary>
    /// Interaction logic for pgAdoptionAnimalList.xaml
    /// </summary>
    public partial class pgAdoptionAnimalList : Page
    {
        IAdoptionAnimalManager _adoptionAnimalManager;

        public pgAdoptionAnimalList()
        {
            InitializeComponent();
            _adoptionAnimalManager = new AdoptionAnimalManager();
            try
            {
                dgAnimalList.ItemsSource = _adoptionAnimalManager.RetrieveAdoptionAnimalsByActive(true);
            }
            catch (Exception)
            {

                throw;
            }
            

        }

        private void DgAnimalList_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgAnimalList.Columns.RemoveAt(18);
            dgAnimalList.Columns.RemoveAt(14);
            dgAnimalList.Columns.RemoveAt(13);
            dgAnimalList.Columns.RemoveAt(12);
            dgAnimalList.Columns.RemoveAt(11);
            dgAnimalList.Columns.RemoveAt(10);
            dgAnimalList.Columns.RemoveAt(9);
            dgAnimalList.Columns.RemoveAt(8);
            dgAnimalList.Columns.RemoveAt(7);
            dgAnimalList.Columns.RemoveAt(5);
            dgAnimalList.Columns.RemoveAt(4);

            dgAnimalList.Columns.RemoveAt(3);
            dgAnimalList.Columns.RemoveAt(2);
            dgAnimalList.Columns.RemoveAt(1);
            dgAnimalList.Columns.RemoveAt(0);

            dgAnimalList.Columns[0].Header = "Is Spayed or Nuetered";
            dgAnimalList.Columns[2].Header = "Animal Name";
            dgAnimalList.Columns[3].Header = "Animal Breed";
            dgAnimalList.Columns[4].Header = "Arrival Date";
            dgAnimalList.Columns[5].Header = "Currrently Housed";
            dgAnimalList.Columns[6].Header = "Adoptable";
            dgAnimalList.Columns[7].Header = "Animal Species";


        }
    }
}
