using DataTransferObjects;
using LogicLayer;
using PresentationUtilityCode;
using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;

namespace WPFPresentationLayer.RecruitingPages
{
    /// <summary>
    /// Interaction logic for ListNewRequests.xaml
    /// </summary>
    public partial class ListNewRequests : Page
    {
        private IRequestManager _requestManager;
        private List<DepartmentRequest> _newRequests;
        private PetUniverseUser _user;
        private List<string> _userDepartmentIDs;
        public ListNewRequests(PetUniverseUser user)
        {
            _user = user;
            _requestManager = new RequestManager();
            populateDepartments();
            InitializeComponent();
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/02/22
        /// Approver: Derek Taylor
        ///
        /// Helper method to populate an employee user's departments, based on their userID
        /// </summary>
        /// <remarks>
        /// Updater:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        private void populateDepartments()
        {
            try
            {
                _userDepartmentIDs = _requestManager.RetrieveAllDepartmentIDsByUserID(_user.PUUserID);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, ex.InnerException.Message);
            }
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/02/13
        /// Approver: Derek Taylor
        ///
        /// Load Method to retrieve a list of New Requests when the NewRequestTab loads, and bind 
        /// that list to the datagrid.
        /// </summary>
        /// <remarks>
        /// Updater:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgNewRequestList_Loaded(object sender, RoutedEventArgs e)
        {
            try
            {
                if (_user.IsEmployee())
                {
                    _newRequests = _requestManager.RetrieveNewRequestsByDepartmentID(_userDepartmentIDs);
                    dgNewRequestList.ItemsSource = _newRequests.DistinctRequests();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, ex.InnerException.Message);
            }
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/02/13
        /// Approver: Derek Taylor
        ///
        /// Method for filtering which columns to fill once the DataGrid for NewRequests is given a source
        /// </summary>
        /// <remarks>
        /// Updater:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        /// /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgNewRequestList_AutoGeneratedColumns(object sender, EventArgs e)
        {
            //dgNewRequestList.Columns.RemoveAt(13);
            dgNewRequestList.Columns.RemoveAt(11);
            dgNewRequestList.Columns.RemoveAt(10);
            dgNewRequestList.Columns.RemoveAt(9);
            dgNewRequestList.Columns.RemoveAt(6);
            dgNewRequestList.Columns.RemoveAt(5);
            dgNewRequestList.Columns.RemoveAt(4);
            dgNewRequestList.Columns.RemoveAt(3);
            dgNewRequestList.Columns.RemoveAt(0);
            dgNewRequestList.Columns[3].DisplayIndex = 4;
            dgNewRequestList.Columns[3].Header = "Topic";
            dgNewRequestList.Columns[0].DisplayIndex = 1;
            dgNewRequestList.Columns[0].Header = "Requested By";
            dgNewRequestList.Columns[2].DisplayIndex = 0;
            dgNewRequestList.Columns[2].Header = "Request";
            dgNewRequestList.Columns[1].DisplayIndex = 2;
            dgNewRequestList.Columns[1].Header = "Requested Of";
            dgNewRequestList.Columns[4].DisplayIndex = 3;
            dgNewRequestList.Columns[4].Header = "Date";
        }

    }
}
