using DataTransferObjects;
using LogicLayer;
using PresentationUtilityCode;
using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;

namespace WPFPresentationLayer.RecruitingPages
{
    /// <summary>
    /// Interaction logic for ListActiveRequests.xaml
    /// </summary>
    public partial class ListActiveRequests : Page
    {
        private IRequestManager _requestManager;
        private List<DepartmentRequest> _activeRequests;
        private PetUniverseUser _user;
        private List<string> _userDepartmentIDs;
        public ListActiveRequests(PetUniverseUser user)
        {
            _user = user;
            _requestManager = new RequestManager();
            populateDepartments();
            InitializeComponent();
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/02/22
        /// Approver: Derek Taylor
        ///
        /// Helper method to populate an employee user's departments, based on their userID
        /// </summary>
        /// <remarks>
        /// Updater:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        private void populateDepartments()
        {
            try
            {
                _userDepartmentIDs = _requestManager.RetrieveAllDepartmentIDsByUserID(this._user.PUUserID);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, ex.InnerException.Message);
            }
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/02/13
        /// Approver: Derek Taylor
        ///
        /// Load Method to retrieve a list of Active Requests when the ActiveRequestTab loads, and bind 
        /// that list to the datagrid.
        /// </summary>
        /// <remarks>
        /// Updater:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgActiveRequestList_Loaded(object sender, RoutedEventArgs e)
        {
            try
            {
                if (dgActiveRequestList.ItemsSource == null)
                {
                    _activeRequests = _requestManager.RetrieveActiveRequestsByDepartmentID(_userDepartmentIDs);
                    dgActiveRequestList.ItemsSource = _activeRequests.DistinctRequests();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, ex.InnerException.Message);
            }
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/02/13
        /// Approver: Derek Taylor
        ///
        /// Method for filtering which columns to fill once the DataGrid for ActiveRequests is given a source
        /// </summary>
        /// <remarks>
        /// Updater:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        /// /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgActiveRequestList_AutoGeneratedColumns(object sender, EventArgs e)
        {
            //dgActiveRequestList.Columns.RemoveAt(13);
            dgActiveRequestList.Columns.RemoveAt(11);
            dgActiveRequestList.Columns.RemoveAt(10);
            dgActiveRequestList.Columns.RemoveAt(9);
            dgActiveRequestList.Columns.RemoveAt(6);
            dgActiveRequestList.Columns.RemoveAt(5);
            dgActiveRequestList.Columns.RemoveAt(4);
            dgActiveRequestList.Columns.RemoveAt(3);
            dgActiveRequestList.Columns.RemoveAt(0);
            dgActiveRequestList.Columns[3].DisplayIndex = 4;
            dgActiveRequestList.Columns[3].Header = "Topic";
            dgActiveRequestList.Columns[0].DisplayIndex = 1;
            dgActiveRequestList.Columns[0].Header = "Requested By";
            dgActiveRequestList.Columns[2].DisplayIndex = 0;
            dgActiveRequestList.Columns[2].Header = "Request";
            dgActiveRequestList.Columns[1].DisplayIndex = 2;
            dgActiveRequestList.Columns[1].Header = "Requested Of";
            dgActiveRequestList.Columns[4].DisplayIndex = 3;
            dgActiveRequestList.Columns[4].Header = "Date";
        }
    }
}
