using LogicLayer;
using LogicLayerInterfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WPFPresentationLayer.VolunteerPages
{
    /// <summary>
	/// Creator: Josh J
	/// Created: 2020/02/24
	/// Approver
	///
	/// Page for viewing all the volunteers
	/// </summary>
    public partial class ViewVolunteers : Page
    {
        public ViewVolunteers()
        {
            InitializeComponent();
            _volunteerManager = new VolunteerManager();
            populateVolunteers();
        }

        // private Volunteer _volunteer = null;
        private IVolunteerManager _volunteerManager;
        private string firstName = "";
        private string lastName = "";

	    /// Creator: Gabi L
	    /// Created: 2020/02/12
	    /// <summary>
	    /// Approver: Josh
	    /// 
	    /// Actual summary of the method
	    /// </summary>
	    ///
	    /// <remarks>
	    /// Updated by: Josh Jackson
	    /// Updated: 2020/02/28
	    /// Update: Changed from a tab onFocus event to a method that is called when the page is loaded
	    /// </remarks>
        private void populateVolunteers()
        {
            try
            {
                if (dgVolunteerList.ItemsSource == null)
                {
                    dgVolunteerList.ItemsSource = _volunteerManager.RetrieveVolunteerListByActive();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message + "\n\n" + ex.InnerException.Message);
            }
        }


        /// Creator: Gabi L
	    /// Created: 2020/02/12
	    /// <summary>
	    /// Approver: Josh
	    /// 
	    /// Populates list columns names
	    /// </summary>
	    ///
	    /// <remarks>
	    /// Updated by: 
	    /// Updated:
	    /// Update: 
	    /// </remarks>
        private void dgVolunteerList_AutoGeneratedColumns(object sender, EventArgs e)
        {

            dgVolunteerList.Columns.Remove(dgVolunteerList.Columns[6]);


            dgVolunteerList.Columns[0].Header = "VolunteerID";
            dgVolunteerList.Columns[1].Header = "First Name";
            dgVolunteerList.Columns[2].Header = "Last Name";
            dgVolunteerList.Columns[3].Header = "Email";
            dgVolunteerList.Columns[4].Header = "Phone Number";
            dgVolunteerList.Columns[5].Header = "Work History";


        }


        /// Creator: Gabi L
	    /// Created: 2020/02/12
	    /// <summary>
	    /// Approver: Josh
	    /// 
	    /// Saves the volunteer record and adds it to database
	    /// </summary>
	    ///
	    /// <remarks>
	    /// Updated by: Josh Jackson
	    /// Updated: 2020/02/28
	    /// Update: Changed how the save button interacts with the pages
	    /// </remarks>
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            this.NavigationService?.Navigate(new AddEditVolunteer(_volunteerManager));
        }

        /// <summary>
        /// NAME: Josh Jackson
        /// DATE: 02/14/2020
        /// Checked By: 
        /// This clears the search box upon clicking if text is default
        /// </summary>
        /// <remarks>
        /// UPDATED BY: 
        /// UPDATE DATE: 
        /// WHAT WAS CHANGED: 
        /// </remarks>
        private void TxtSearch_GotFocus(object sender, RoutedEventArgs e)
        {
            if (txtSearch.Text == "Volunteer Name here")
            {
                txtSearch.Text = "";
            }
        }

        /// <summary>
        /// NAME: Josh Jackson
        /// DATE: 02/14/2020
        /// Checked By: 
        /// this method splits the string taken from the search box into two strings firstName and lastName
        /// and then passes those values to the logic layer to query a volunteer record
        /// </summary>
        /// <remarks>
        /// UPDATED BY: 
        /// UPDATE DATE: 
        /// WHAT WAS CHANGED: 
        /// </remarks>
        private void BtnSearch_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                string wholeName = txtSearch.Text.ToString();
                // this checks for a space in whole name and splits at the space into an array, the values in the newly created array are assigned to firstName and lastName respectively
                if (wholeName.Contains(" "))
                {
                    string[] tmp = wholeName.Split(' ');
                    firstName = tmp[0];
                    lastName = tmp[1].Trim();
                    dgVolunteerList.ItemsSource = _volunteerManager.GetVolunteerByName(firstName, lastName);
                }
                else
                {
                    MessageBox.Show("Incorrect name format, try again");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message + "\n\n" + ex.InnerException.Message);
            }
        }
    }
}
