using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using LogicLayer;
using LogicLayerInterfaces;

namespace WPFPresentationLayer.InventoryPages.Items
{
    /// <summary>
    /// Creator: Brandyn T. Coverdill
    /// Created: 2020/02/22
    /// Approver: 
    /// Approver: 
    ///
    /// Page class that handles viewing Inventory.
    /// </summary>
    public partial class ViewInventory : Page
    {

        private IItemManager _itemManager;

        public ViewInventory()
        {
            _itemManager = new ItemManager();
            InitializeComponent();
        }

        /// <summary>
        /// Creator: Brandyn T. Coverdill
        /// Created: 2020/02/23
        /// Approver: 
        /// Approver:  
        ///
        /// Method that generates the columns for the view inventory datagrid.
        /// </summary>
        ///
        /// <remarks>
        /// Updated By: 
        /// Updated: 
        /// Update:
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgViewInventory_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgViewInventory.Columns[0].Header = "Item ID";
            dgViewInventory.Columns[1].Header = "Item Name";
            dgViewInventory.Columns[2].Header = "Item Quantity";
            dgViewInventory.Columns[3].Header = "Category";

            foreach (var column in this.dgViewInventory.Columns)
            {
                column.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            }
        }

        /// <summary>
        /// Creator: Brandyn T. Coverdill
        /// Created: 2020/02/23
        /// Approver: 
        /// Approver:  
        ///
        /// When datagrid is loaded, add items to the datagrid.
        /// </summary>
        ///
        /// <remarks>
        /// Updated By: 
        /// Updated: 
        /// Update:
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgViewInventory_Loaded(object sender, RoutedEventArgs e)
        {
            dgViewInventory.ItemsSource = _itemManager.retrieveItems();
        }



        /// <summary>
        /// Creator: Brandyn T. Coverdill
        /// Created: 2020/03/01
        /// Approver: 
        /// Approver:  
        ///
        /// This Button shows the Add Item Screen.
        /// </summary>
        ///
        /// <remarks>
        /// Updated By: 
        /// Updated: 
        /// Update:
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnAddItems_Click(object sender, RoutedEventArgs e)
        {
            this.NavigationService?.Navigate(new AddItems());
        }
    }
}
