using DataTransferObjects;
using LogicLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WPFPresentationLayer.InventoryPages
{
    /// <summary>
    /// Interaction logic for ViewOrders.xaml
    /// </summary>
    public partial class ViewOrders : Page
    {
        private OrderAccessor _orderManager = new OrderAccessor();
        private List<Order> _orders;
        private List<Order> _currentOrders;

        public ViewOrders()
        {
            InitializeComponent();
        }

        private void Grid_Loaded(object sender, RoutedEventArgs e)
        {
            try
            {
                _orders = (List<Order>)_orderManager.RetrieveOrders();

                if (_currentOrders == null)
                {
                    _currentOrders = _orders;
                }

                btnAddOrder.Visibility = Visibility.Visible;
                dgOrders.ItemsSource = _currentOrders;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void BtnAddOrder_Click(object sender, RoutedEventArgs e)
        {
            this.NavigationService?.Navigate(new ViewAddOrder());
        }

        private void dgOrders_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgOrders.Columns[0].Header = "Order ID";
            dgOrders.Columns[1].Header = "Employee ID";
            //dgOrders.Columns[2].Visible = false; this is supposed to work?!?
            foreach (var column in this.dgOrders.Columns)
            {
                column.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            }
        }
    }
}
