using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DataTransferObjects;
using LogicLayer;
using LogicLayerInterfaces;
using PresentationUtilityCode;

namespace WPFPresentationLayer.InventoryPages.Items
{
    /// <summary>
    /// Creator: Brandyn T. Coverdill
    /// Created: 2020/02/22
    /// Approver: Dalton Reierson
    /// Approver:  Jesse Tomash
    ///
    /// Page class that handles viewing Inventory.
    /// </summary>
    public partial class ViewInventory : Page
    {

        private IItemManager _itemManager;

        public ViewInventory()
        {
            _itemManager = new ItemManager();
            InitializeComponent();
        }

        /// <summary>
        /// Creator: Brandyn T. Coverdill
        /// Created: 2020/02/23
        /// Approver: Dalton Reierson
        /// Approver:   Jesse Tomash
        ///
        /// Method that generates the columns for the view inventory datagrid.
        /// </summary>
        ///
        /// <remarks>
        /// Updated By: Brandyn T. Coverdill
        /// Updated: 2020/03/03
        /// Update: The Description field was blank, so I modified it to where it gives a description of the item.
        /// Approver: Dalton Reierson
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgViewInventory_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgViewInventory.Columns[0].Header = "Item ID";
            dgViewInventory.Columns[1].Header = "Item Name";
            dgViewInventory.Columns[2].Header = "Item Quantity";
            dgViewInventory.Columns[3].Header = "Category";
            dgViewInventory.Columns[4].Header = "Description";

            foreach (var column in this.dgViewInventory.Columns)
            {
                column.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            }
        }

        /// <summary>
        /// Creator: Brandyn T. Coverdill
        /// Created: 2020/02/23
        /// Approver: Dalton Reierson
        /// Approver:   Jesse Tomash
        ///
        /// When datagrid is loaded, add items to the datagrid.
        /// </summary>
        ///
        /// <remarks>
        /// Updated By: 
        /// Updated: 
        /// Update:
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgViewInventory_Loaded(object sender, RoutedEventArgs e)
        {
            dgViewInventory.ItemsSource = _itemManager.retrieveItems();
        }



        /// <summary>
        /// Creator: Brandyn T. Coverdill
        /// Created: 2020/03/01
        /// Approver: Dalton Reierson
        /// Approver:  Jesse Tomash
        ///
        /// This Button shows the Add Item Screen.
        /// </summary>
        ///
        /// <remarks>
        /// Updated By: 
        /// Updated: 
        /// Update:
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnAddItems_Click(object sender, RoutedEventArgs e)
        {
            this.NavigationService?.Navigate(new AddItems());
        }

        /// <summary>
        /// Creator: Brandyn T. Coverdill
        /// Created: 2020/03/03
        /// Approver: Dalton Reierson
        /// Approver:  Jesse Tomash
        ///
        /// This click event opens the view item detail screen.
        /// </summary>
        ///
        /// <remarks>
        /// Updated By: 
        /// Updated: 
        /// Update:
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnViewItem_Click(object sender, RoutedEventArgs e)
        {
            Item item = (Item) dgViewInventory.SelectedItem;
            if (dgViewInventory.SelectedItem != null)
            {
                this.NavigationService?.Navigate(new ViewItemDetail(item));
            }
            else
            {
                "Please pick an item to view.".ErrorMessage();
            }
        }
    }
}
